name: Generate Release from tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore WDSSuperMenu/WDSSuperMenu.csproj

      - name: Build specific project
        run: dotnet build WDSSuperMenu/WDSSuperMenu.csproj --configuration Release --no-restore

      - name: Publish specific project
        run: dotnet publish WDSSuperMenu/WDSSuperMenu.csproj --configuration Release --no-build --output ./publish

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Compile Inno Setup script
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer.iss

      - name: Upload Installer to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: .github/release-notes.md
          files: output/WDSSuperMenuInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
