name: Generate Release from tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore WDSSuperMenu/WDSSuperMenu.csproj

      - name: Set up Git tag version
        id: version
        run: |
          $version = $env:GITHUB_REF.Replace("refs/tags/v", "")
          $versionWithV = "v$version"
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Output "VERSION_WITH_V=v$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Build specific project
        run: |
          dotnet build WDSSuperMenu/WDSSuperMenu.csproj `
            --configuration Release `
            --no-restore `
            -p:Version=${{ env.VERSION }} `
            -p:AssemblyVersion=${{ env.VERSION }} `
            -p:FileVersion=${{ env.VERSION }} `
            -p:InformationalVersion=${{ env.VERSION }}

      - name: Publish specific project
        run: |
          dotnet publish WDSSuperMenu/WDSSuperMenu.csproj `
            --configuration Release `
            --no-build `
            --output ./publish `
            -p:Version=${{ env.VERSION }} `
            -p:AssemblyVersion=${{ env.VERSION }} `
            -p:FileVersion=${{ env.VERSION }} `
            -p:InformationalVersion=${{ env.VERSION }}

      - name: Zip the publish folder
        run: Compress-Archive -Path ./publish/* -DestinationPath ./WDSSuperMenu-${{ env.VERSION_WITH_V }}-Portable.zip

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile Inno Setup script
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' "/DAppVersion=${{ env.VERSION_WITH_V }}" installer.iss

      - name: Upload Installer and ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: .github/release-notes.md
          files: |
            output/WDSSuperMenu-${{ env.VERSION_WITH_V }}-Installer.exe
            ./WDSSuperMenu-${{ env.VERSION_WITH_V }}-Portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
